version: "3"
services:
  mysql:
    # Após a inicialização do container executar o comando abaixo
    # docker exec -i mysql sh -c 'exec mysql -u root -p"$MYSQL_ROOT_PASSWORD" < /mnt/app/script-mysql.sql'
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./_volumes/mysql/conf.d:/etc/mysql/conf.d
      - ./_volumes/scripts:/mnt/app
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  postgres:
    build:
      context: ./_volumes/dockerfiles
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authdb